spring:
  application:
    name: fool-cloud-example
server:
  port: 9528
  servlet:
    context-path: /example    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9526/eureka/eureka/
    enabled: true

#security:
#  basic:
#    enabled: false