spring:
  application:
    name: fool-cloud-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.100:3307/internethsp?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
  #redis host名字
  redis:
    host:  10.10.10.242
    #redis端口号
    port: 6379
    #redis 密码
    password:
  # 心跳检测时间(ms). 默认为 30000
server:
  port: 9528
  servlet:
    context-path: /example    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9526/eureka/eureka/
    enabled: true

#security:
#  basic:
#    enabled: false
tx-lcn:
  client:
    manager-address: 127.0.0.1:9529
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}