server:
  #端口号
  port: 8105

##数据库连接信息
spring:
  #  profiles:
  #    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 服务名小写
          lower-case-service-id: true
      routes:
    # =====================================
      - id: SERVICEBASIC
          # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://FOOL-CLOUD-EXAMPLE
        predicates:
        - Path=/example/**
        filters:
        - StripPrefix=0
     
  #====================================
  application:
    name: inter-hsp-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9526/eureka/eureka/
    enabled: true

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug 

           
  
